getwd()
dir.create("raw_data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results")
dir.create("Tasks")
dir.create("plots ")
str(patient_info)
class(patient_info$age)
class(patient_info$gender)
class(patient_info$diagnosis)
class(patient_info$bmi)
class(patient_info$smoker)
class(patient_info$patient_id)
patient_info$Smoking_binary <- as.factor(patient_info$smoker)
patient_info$Smoking_binary <- ifelse(patient_info$smoker=="Yes", 1, 0)
write.csv(patient_info,file = "raw_data/patient_info_clean.csv")
save.image(file = "full_workspace.RData")
